# Generated by Django 4.1.1 on 2022-10-01 13:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=50)),
                ("isHidden", models.BooleanField(default=False)),
                ("isDelete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
